### ISSUE TITLE
Install attempt on Wasta 20.04

### ISSUE THREAD

**Issue by cmahte** [wasta-linux/map-creator-snap#1]
I didn't have any wine pre-installed.  There was no detection or suggestion that this was a pre-req or not part of the setup. Now i'm looking at this screen that doesn't seem to be going anywhere. 

------ snip ------
michael@Revelation1-19:~$ which snap || sudo apt-get snapd
/usr/bin/snap
michael@Revelation1-19:~$ snap install map-creator-unofficial --beta
Automatically connect eligible plugs and slots of snap "map-creator-unofficial" 
------ snip ------

**Comment by cmahte** [comment]
5 minutes later it wasn't lack of wine, and the errors give a bit more information: 

michael@Revelation1-19:~$ which snap || sudo apt-get snapd
/usr/bin/snap
michael@Revelation1-19:~$ snap install map-creator-unofficial --beta
Automatically connect eligible plugs and slots of snap "map-creator-unofficial" error: cannot perform the following tasks:
- Download snap "wine-platform-runtime" (301) from channel "stable" (the download has been cancelled: context canceled)
- Download snap "gnome-3-28-1804" (161) from channel "stable" (the download has been cancelled: context canceled)
- Download snap "wine-platform-6-stable" (19) from channel "stable" (the download has been cancelled: context canceled)
michael@Revelation1-19:~$ 

My internet connection is flaky... I've got a flaky Wireless router and a Signal to noise issue on the incoming line. so unless this is repeated by someone/somewhere else, it's probably all local issues.

**Comment by cmahte** [comment]
The 2nd time through there's a spinning cursor. I didn't see it (don't think it was there) on the first attempt, but besides that the process is silent. Is there a way to enable "verbose" or "progress"? I get nervous when i run unknown or beta code and it goes silent for long.

**Comment by cmahte** [comment]
map-creator-unofficial (beta) 2.3.2 from Nate (n8marti) installed

Started Map Creator from launcher. but where is it in the launcher menu ... I expected it in Graphics but only found it in "all applications".

**Comment by cmahte** [comment]
Install is complete. attempting a new map based on Blank maps from "The Sunday School Commission of the Anglican Diocese of New York" works created and copyrighted between 1908-1918ish. These are black/white maps that are intended to be included in works where color printing is not possible, like print on demand.

**Comment by cmahte** [comment]
Wine doesn't see the entire computer.  My system is in an SSD drive (which wine shows at '/'), but all my projects are in a magnetic drive mounted at /mnt/stuff.  wine sees /mnt but displays empty folder. This is probably way up the food chain... and not a show stopper.

**Comment by cmahte** [comment]
not a bug or request, just putting this into comments for watchers. 

C: drive is located at

~/snap/map-creator-unofficial/common/.wine/drive_c/

**Comment by cmahte** [comment]
![image](https://user-images.githubusercontent.com/11809394/171025351-629cd291-5d87-4223-a570-d1642a9376b6.png)

With no issues.

**Comment by cmahte** [comment]
Great work! other than the notes above... none of which are problems just perceptions.... perfect.

**Comment by cmahte** [comment]
One other thing, I use pretty big monitors (32" TV's) and the default system font in wine is small.  So I want to run control panel and adjust the interface a bit.. but wine doesn't seem to be installed.

---- snip ----
`$ wine

Command 'wine' not found, but can be installed with:

sudo apt install wine              # version 5.0-3ubuntu1, or
sudo apt install wine-development  # version 5.5-3ubuntu1`
--- snip ---
even though I saw evidence that the control panel is present browsing the folder structure.  This is a wine thing, not map-creator, but I don't see any link to control panel or a way to start a wine session to find it in the launcher...

**Comment by n8marti** [comment]
> map-creator-unofficial (beta) 2.3.2 from Nate (n8marti) installed
> 
> Started Map Creator from launcher. but where is it in the launcher menu ... I expected it in Graphics but only found it in "all applications".

That's a good suggestion. It's only in the Education category, but Graphics makes sense, too. I'll update that.

**Comment by n8marti** [comment]
> Wine doesn't see the entire computer. My system is in an SSD drive (which wine shows at '/'), but all my projects are in a magnetic drive mounted at /mnt/stuff. wine sees /mnt but displays empty folder. This is probably way up the food chain... and not a show stopper.

You can gain access to /mnt and /media by connecting the 'removable-drives' plug:
```bash
snap connect map-creator-unofficial:removable-media
```
This is unfortunately [not automatic](https://snapcraft.io/docs/removable-media-interface).

**Comment by n8marti** [comment]
> One other thing, I use pretty big monitors (32" TV's) and the default system font in wine is small. So I want to run control panel and adjust the interface a bit.. but wine doesn't seem to be installed.
> 
> ---- snip ---- `$ wine
> 
> Command 'wine' not found, but can be installed with:
> 
> sudo apt install wine # version 5.0-3ubuntu1, or sudo apt install wine-development # version 5.5-3ubuntu1` --- snip --- even though I saw evidence that the control panel is present browsing the folder structure. This is a wine thing, not map-creator, but I don't see any link to control panel or a way to start a wine session to find it in the launcher...

Wine is only available within the snap package, so there are a few sub-commands available within the app for this:
```bash
$ snap info map-creator-unofficial
# ...
  - map-creator-unofficial.init         # initialize the wine prefix and exit
  - map-creator-unofficial.map-creator  # main app command
  - map-creator-unofficial.wine         # run wine within the app's confinement
  - map-creator-unofficial.winecfg      # direct command for winecfg
  - map-creator-unofficial.winetricks   # direct command for winetricks
# ...
```
So to open the Control Panel you can do:
```bash
map-creator-unofficial.wine control
```
![Capture d’écran du 2022-05-31 14-33-27](https://user-images.githubusercontent.com/23388501/171186169-37af2286-5c69-40b1-a493-c6eceb689e92.png)

But in your case I think you want to use ```map-creator-unofficial.winecfg``` to change the Screen resolution (dpi) in the "Graphics" tab.
